import React, { useRef, useEffect, useState } from "react";
import * as d3 from "d3";
import { useSpring, animated } from '@react-spring/web'
import '../../../styles/shared.sass'

export const Linear = (props) => {

    const [title, setTitle] = useState(
        (props.title) ? props.title : "Linear chart title"
    );

    const [data, setData] = useState(
        (props.data) ? props.data.map(element => ({ ...element, date: new Date(element.date) })).sort((a, b) => a.date - b.date) :
            [
                {
                    "open": 3.77,
                    "high": 3.7765,
                    "low": 3.756,
                    "close": 3.768,
                    "volume": 20252178.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.768,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-24T00:00:00+0000"
                },
                {
                    "open": 3.7405,
                    "high": 3.766,
                    "low": 3.7315,
                    "close": 3.7605,
                    "volume": 19229828.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.7605,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-23T00:00:00+0000"
                },
                {
                    "open": 3.7355,
                    "high": 3.755,
                    "low": 3.7175,
                    "close": 3.7465,
                    "volume": 27335636.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.7465,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-22T00:00:00+0000"
                },
                {
                    "open": 3.7135,
                    "high": 3.7275,
                    "low": 3.691,
                    "close": 3.726,
                    "volume": 17106225.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.726,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-21T00:00:00+0000"
                },
                {
                    "open": 3.73,
                    "high": 3.7675,
                    "low": 3.726,
                    "close": 3.734,
                    "volume": 27462716.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.734,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-20T00:00:00+0000"
                },
                {
                    "open": 3.7,
                    "high": 3.729,
                    "low": 3.69,
                    "close": 3.7235,
                    "volume": 65573690.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.7235,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-17T00:00:00+0000"
                },
                {
                    "open": 3.6715,
                    "high": 3.7295,
                    "low": 3.6715,
                    "close": 3.69,
                    "volume": 34850709.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.69,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-16T00:00:00+0000"
                },
                {
                    "open": 3.689,
                    "high": 3.7,
                    "low": 3.656,
                    "close": 3.67,
                    "volume": 39983364.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.67,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-15T00:00:00+0000"
                },
                {
                    "open": 3.65,
                    "high": 3.6945,
                    "low": 3.6375,
                    "close": 3.6835,
                    "volume": 40160928.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6835,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-14T00:00:00+0000"
                },
                {
                    "open": 3.622,
                    "high": 3.65,
                    "low": 3.619,
                    "close": 3.65,
                    "volume": 26206164.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.65,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-13T00:00:00+0000"
                },
                {
                    "open": 3.5905,
                    "high": 3.6345,
                    "low": 3.581,
                    "close": 3.609,
                    "volume": 42654165.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.609,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-10T00:00:00+0000"
                },
                {
                    "open": 3.552,
                    "high": 3.597,
                    "low": 3.547,
                    "close": 3.597,
                    "volume": 24846238.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.597,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-09T00:00:00+0000"
                },
                {
                    "open": 3.519,
                    "high": 3.5855,
                    "low": 3.4875,
                    "close": 3.5485,
                    "volume": 35057254.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5485,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-08T00:00:00+0000"
                },
                {
                    "open": 3.52,
                    "high": 3.5585,
                    "low": 3.488,
                    "close": 3.521,
                    "volume": 129335715.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.521,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-07T00:00:00+0000"
                },
                {
                    "open": 3.579,
                    "high": 3.5895,
                    "low": 3.5345,
                    "close": 3.54,
                    "volume": 50964313.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.54,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-06T00:00:00+0000"
                },
                {
                    "open": 3.5975,
                    "high": 3.6105,
                    "low": 3.56,
                    "close": 3.5775,
                    "volume": 47557948.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5775,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-03T00:00:00+0000"
                },
                {
                    "open": 3.504,
                    "high": 3.596,
                    "low": 3.4955,
                    "close": 3.585,
                    "volume": 38709786.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.585,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-02T00:00:00+0000"
                },
                {
                    "open": 3.4885,
                    "high": 3.5155,
                    "low": 3.46,
                    "close": 3.5005,
                    "volume": 41262589.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5005,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-11-01T00:00:00+0000"
                },
                {
                    "open": 3.5055,
                    "high": 3.544,
                    "low": 3.4295,
                    "close": 3.466,
                    "volume": 55140027.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.466,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.06561,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-31T00:00:00+0000"
                },
                {
                    "open": 3.5,
                    "high": 3.5765,
                    "low": 3.4715,
                    "close": 3.5695,
                    "volume": 70759794.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5695,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-30T00:00:00+0000"
                },
                {
                    "open": 3.545,
                    "high": 3.563,
                    "low": 3.4575,
                    "close": 3.481,
                    "volume": 53188968.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.481,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-27T00:00:00+0000"
                },
                {
                    "open": 3.44,
                    "high": 3.52,
                    "low": 3.4055,
                    "close": 3.511,
                    "volume": 32180826.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.511,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-26T00:00:00+0000"
                },
                {
                    "open": 3.4005,
                    "high": 3.5015,
                    "low": 3.345,
                    "close": 3.461,
                    "volume": 87296666.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.461,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-25T00:00:00+0000"
                },
                {
                    "open": 3.441,
                    "high": 3.4425,
                    "low": 3.3525,
                    "close": 3.3815,
                    "volume": 170866733.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.3815,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-24T00:00:00+0000"
                },
                {
                    "open": 3.4635,
                    "high": 3.4745,
                    "low": 3.3875,
                    "close": 3.4215,
                    "volume": 180152067.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4215,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-23T00:00:00+0000"
                },
                {
                    "open": 3.48,
                    "high": 3.503,
                    "low": 3.4515,
                    "close": 3.4565,
                    "volume": 65331121.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4565,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-20T00:00:00+0000"
                },
                {
                    "open": 3.51,
                    "high": 3.524,
                    "low": 3.471,
                    "close": 3.5085,
                    "volume": 31323285.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5085,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-19T00:00:00+0000"
                },
                {
                    "open": 3.557,
                    "high": 3.572,
                    "low": 3.511,
                    "close": 3.511,
                    "volume": 34988893.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.511,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-18T00:00:00+0000"
                },
                {
                    "open": 3.566,
                    "high": 3.5875,
                    "low": 3.5305,
                    "close": 3.572,
                    "volume": 16218637.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.572,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-17T00:00:00+0000"
                },
                {
                    "open": 3.54,
                    "high": 3.591,
                    "low": 3.501,
                    "close": 3.576,
                    "volume": 26850606.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.576,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-16T00:00:00+0000"
                },
                {
                    "open": 3.57,
                    "high": 3.584,
                    "low": 3.494,
                    "close": 3.513,
                    "volume": 41393175.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.513,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-13T00:00:00+0000"
                },
                {
                    "open": 3.643,
                    "high": 3.643,
                    "low": 3.5695,
                    "close": 3.587,
                    "volume": 21374765.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.587,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-12T00:00:00+0000"
                },
                {
                    "open": 3.5845,
                    "high": 3.631,
                    "low": 3.5735,
                    "close": 3.6105,
                    "volume": 27641321.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6105,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-11T00:00:00+0000"
                },
                {
                    "open": 3.55,
                    "high": 3.628,
                    "low": 3.54,
                    "close": 3.607,
                    "volume": 29429951.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.607,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-10T00:00:00+0000"
                },
                {
                    "open": 3.567,
                    "high": 3.583,
                    "low": 3.508,
                    "close": 3.5125,
                    "volume": 31893814.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5125,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-09T00:00:00+0000"
                },
                {
                    "open": 3.5665,
                    "high": 3.631,
                    "low": 3.5595,
                    "close": 3.6095,
                    "volume": 23749011.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6095,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-06T00:00:00+0000"
                },
                {
                    "open": 3.555,
                    "high": 3.5735,
                    "low": 3.4965,
                    "close": 3.5505,
                    "volume": 28122494.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5505,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-05T00:00:00+0000"
                },
                {
                    "open": 3.54,
                    "high": 3.5475,
                    "low": 3.478,
                    "close": 3.5225,
                    "volume": 36554010.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5225,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-04T00:00:00+0000"
                },
                {
                    "open": 3.555,
                    "high": 3.6345,
                    "low": 3.543,
                    "close": 3.555,
                    "volume": 30177146.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.555,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-03T00:00:00+0000"
                },
                {
                    "open": 3.6205,
                    "high": 3.66,
                    "low": 3.5645,
                    "close": 3.5725,
                    "volume": 36166144.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5725,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-10-02T00:00:00+0000"
                },
                {
                    "open": 3.6315,
                    "high": 3.662,
                    "low": 3.6,
                    "close": 3.6185,
                    "volume": 42092018.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6185,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-29T00:00:00+0000"
                },
                {
                    "open": 3.51,
                    "high": 3.6525,
                    "low": 3.5005,
                    "close": 3.65,
                    "volume": 53172108.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.65,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-28T00:00:00+0000"
                },
                {
                    "open": 3.4425,
                    "high": 3.515,
                    "low": 3.435,
                    "close": 3.4945,
                    "volume": 22567673.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4945,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-27T00:00:00+0000"
                },
                {
                    "open": 3.434,
                    "high": 3.462,
                    "low": 3.3965,
                    "close": 3.4345,
                    "volume": 28656948.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4345,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-26T00:00:00+0000"
                },
                {
                    "open": 3.46,
                    "high": 3.5125,
                    "low": 3.431,
                    "close": 3.45,
                    "volume": 26719441.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.45,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-25T00:00:00+0000"
                },
                {
                    "open": 3.487,
                    "high": 3.5195,
                    "low": 3.464,
                    "close": 3.482,
                    "volume": 33356450.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.482,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-22T00:00:00+0000"
                },
                {
                    "open": 3.49,
                    "high": 3.513,
                    "low": 3.451,
                    "close": 3.5065,
                    "volume": 34697506.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5065,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-21T00:00:00+0000"
                },
                {
                    "open": 3.49,
                    "high": 3.542,
                    "low": 3.463,
                    "close": 3.523,
                    "volume": 22734420.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.523,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-20T00:00:00+0000"
                },
                {
                    "open": 3.4325,
                    "high": 3.479,
                    "low": 3.4325,
                    "close": 3.464,
                    "volume": 16094874.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.464,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-19T00:00:00+0000"
                },
                {
                    "open": 3.48,
                    "high": 3.503,
                    "low": 3.4255,
                    "close": 3.4455,
                    "volume": 20311485.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4455,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-18T00:00:00+0000"
                },
                {
                    "open": 3.55,
                    "high": 3.5695,
                    "low": 3.467,
                    "close": 3.4915,
                    "volume": 69443170.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4915,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-15T00:00:00+0000"
                },
                {
                    "open": 3.45,
                    "high": 3.535,
                    "low": 3.422,
                    "close": 3.5255,
                    "volume": 30244680.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5255,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-14T00:00:00+0000"
                },
                {
                    "open": 3.439,
                    "high": 3.477,
                    "low": 3.425,
                    "close": 3.454,
                    "volume": 19145358.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.454,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-13T00:00:00+0000"
                },
                {
                    "open": 3.446,
                    "high": 3.4575,
                    "low": 3.4235,
                    "close": 3.446,
                    "volume": 51404860.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.446,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-12T00:00:00+0000"
                },
                {
                    "open": 3.4385,
                    "high": 3.46,
                    "low": 3.395,
                    "close": 3.434,
                    "volume": 18335020.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.434,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-11T00:00:00+0000"
                },
                {
                    "open": 3.388,
                    "high": 3.4125,
                    "low": 3.332,
                    "close": 3.408,
                    "volume": 23264628.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.408,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-08T00:00:00+0000"
                },
                {
                    "open": 3.392,
                    "high": 3.4175,
                    "low": 3.352,
                    "close": 3.376,
                    "volume": 21694476.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.376,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-07T00:00:00+0000"
                },
                {
                    "open": 3.466,
                    "high": 3.4775,
                    "low": 3.3875,
                    "close": 3.407,
                    "volume": 32761788.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.407,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-06T00:00:00+0000"
                },
                {
                    "open": 3.5035,
                    "high": 3.532,
                    "low": 3.4695,
                    "close": 3.503,
                    "volume": 21317673.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.503,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-05T00:00:00+0000"
                },
                {
                    "open": 3.541,
                    "high": 3.564,
                    "low": 3.5015,
                    "close": 3.515,
                    "volume": 17345055.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.515,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-04T00:00:00+0000"
                },
                {
                    "open": 3.606,
                    "high": 3.616,
                    "low": 3.5195,
                    "close": 3.5195,
                    "volume": 29668913.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5195,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-09-01T00:00:00+0000"
                },
                {
                    "open": 3.6315,
                    "high": 3.646,
                    "low": 3.5935,
                    "close": 3.602,
                    "volume": 55210602.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.602,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-31T00:00:00+0000"
                },
                {
                    "open": 3.65,
                    "high": 3.6825,
                    "low": 3.625,
                    "close": 3.6285,
                    "volume": 17719408.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6285,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-30T00:00:00+0000"
                },
                {
                    "open": 3.642,
                    "high": 3.65,
                    "low": 3.606,
                    "close": 3.6315,
                    "volume": 24326785.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6315,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-29T00:00:00+0000"
                },
                {
                    "open": 3.569,
                    "high": 3.644,
                    "low": 3.553,
                    "close": 3.6425,
                    "volume": 23025078.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6425,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-28T00:00:00+0000"
                },
                {
                    "open": 3.544,
                    "high": 3.589,
                    "low": 3.53,
                    "close": 3.538,
                    "volume": 16246961.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.538,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-25T00:00:00+0000"
                },
                {
                    "open": 3.5725,
                    "high": 3.585,
                    "low": 3.5235,
                    "close": 3.536,
                    "volume": 19636103.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.536,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-24T00:00:00+0000"
                },
                {
                    "open": 3.5725,
                    "high": 3.603,
                    "low": 3.5255,
                    "close": 3.534,
                    "volume": 18015294.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.534,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-23T00:00:00+0000"
                },
                {
                    "open": 3.595,
                    "high": 3.619,
                    "low": 3.571,
                    "close": 3.5765,
                    "volume": 17301727.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5765,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-22T00:00:00+0000"
                },
                {
                    "open": 3.5515,
                    "high": 3.612,
                    "low": 3.5485,
                    "close": 3.561,
                    "volume": 15213035.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.561,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-21T00:00:00+0000"
                },
                {
                    "open": 3.533,
                    "high": 3.559,
                    "low": 3.509,
                    "close": 3.5515,
                    "volume": 17990188.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5515,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-18T00:00:00+0000"
                },
                {
                    "open": 3.55,
                    "high": 3.586,
                    "low": 3.538,
                    "close": 3.557,
                    "volume": 21767274.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.557,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-17T00:00:00+0000"
                },
                {
                    "open": 3.553,
                    "high": 3.5865,
                    "low": 3.5415,
                    "close": 3.5565,
                    "volume": 11273048.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5565,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-16T00:00:00+0000"
                },
                {
                    "open": 3.599,
                    "high": 3.6055,
                    "low": 3.5405,
                    "close": 3.567,
                    "volume": 13039047.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.567,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-15T00:00:00+0000"
                },
                {
                    "open": 3.6095,
                    "high": 3.632,
                    "low": 3.5805,
                    "close": 3.5965,
                    "volume": 15050762.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5965,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-14T00:00:00+0000"
                },
                {
                    "open": 3.639,
                    "high": 3.6465,
                    "low": 3.5825,
                    "close": 3.5925,
                    "volume": 15252206.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5925,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-11T00:00:00+0000"
                },
                {
                    "open": 3.5745,
                    "high": 3.6655,
                    "low": 3.5685,
                    "close": 3.6475,
                    "volume": 30951098.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6475,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-10T00:00:00+0000"
                },
                {
                    "open": 3.593,
                    "high": 3.6055,
                    "low": 3.535,
                    "close": 3.5495,
                    "volume": 18394679.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5495,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-09T00:00:00+0000"
                },
                {
                    "open": 3.5755,
                    "high": 3.5785,
                    "low": 3.461,
                    "close": 3.523,
                    "volume": 34504136.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.523,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-08T00:00:00+0000"
                },
                {
                    "open": 3.5855,
                    "high": 3.6345,
                    "low": 3.56,
                    "close": 3.621,
                    "volume": 12039266.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.621,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-07T00:00:00+0000"
                },
                {
                    "open": 3.604,
                    "high": 3.62,
                    "low": 3.57,
                    "close": 3.6085,
                    "volume": 23142480.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6085,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-04T00:00:00+0000"
                },
                {
                    "open": 3.5095,
                    "high": 3.5925,
                    "low": 3.505,
                    "close": 3.5855,
                    "volume": 35372540.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5855,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-03T00:00:00+0000"
                },
                {
                    "open": 3.542,
                    "high": 3.584,
                    "low": 3.505,
                    "close": 3.5275,
                    "volume": 50280184.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5275,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-02T00:00:00+0000"
                },
                {
                    "open": 3.6785,
                    "high": 3.698,
                    "low": 3.588,
                    "close": 3.599,
                    "volume": 23019304.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.599,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-08-01T00:00:00+0000"
                },
                {
                    "open": 3.6865,
                    "high": 3.708,
                    "low": 3.675,
                    "close": 3.6835,
                    "volume": 24836675.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6835,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-31T00:00:00+0000"
                },
                {
                    "open": 3.6925,
                    "high": 3.742,
                    "low": 3.6525,
                    "close": 3.6775,
                    "volume": 42564955.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.6775,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-28T00:00:00+0000"
                },
                {
                    "open": 3.655,
                    "high": 3.719,
                    "low": 3.615,
                    "close": 3.708,
                    "volume": 75696900.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.708,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-27T00:00:00+0000"
                },
                {
                    "open": 3.538,
                    "high": 3.655,
                    "low": 3.513,
                    "close": 3.649,
                    "volume": 68036296.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.649,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-26T00:00:00+0000"
                },
                {
                    "open": 3.53,
                    "high": 3.546,
                    "low": 3.51,
                    "close": 3.538,
                    "volume": 17151031.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.538,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-25T00:00:00+0000"
                },
                {
                    "open": 3.43,
                    "high": 3.52,
                    "low": 3.4115,
                    "close": 3.52,
                    "volume": 22719550.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.52,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-24T00:00:00+0000"
                },
                {
                    "open": 3.526,
                    "high": 3.5475,
                    "low": 3.473,
                    "close": 3.5285,
                    "volume": 28121501.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.5285,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-21T00:00:00+0000"
                },
                {
                    "open": 3.4885,
                    "high": 3.5415,
                    "low": 3.486,
                    "close": 3.525,
                    "volume": 22612782.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.525,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-20T00:00:00+0000"
                },
                {
                    "open": 3.53,
                    "high": 3.551,
                    "low": 3.464,
                    "close": 3.498,
                    "volume": 17841799.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.498,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-19T00:00:00+0000"
                },
                {
                    "open": 3.464,
                    "high": 3.514,
                    "low": 3.432,
                    "close": 3.51,
                    "volume": 17919382.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.51,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-18T00:00:00+0000"
                },
                {
                    "open": 3.4385,
                    "high": 3.5,
                    "low": 3.4205,
                    "close": 3.4485,
                    "volume": 15777798.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4485,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-17T00:00:00+0000"
                },
                {
                    "open": 3.49,
                    "high": 3.534,
                    "low": 3.456,
                    "close": 3.4605,
                    "volume": 28331703.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4605,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-14T00:00:00+0000"
                },
                {
                    "open": 3.46,
                    "high": 3.5175,
                    "low": 3.433,
                    "close": 3.4905,
                    "volume": 36818261.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4905,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-13T00:00:00+0000"
                },
                {
                    "open": 3.3425,
                    "high": 3.4735,
                    "low": 3.3425,
                    "close": 3.4735,
                    "volume": 57889645.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.4735,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-12T00:00:00+0000"
                },
                {
                    "open": 3.29,
                    "high": 3.338,
                    "low": 3.2615,
                    "close": 3.3345,
                    "volume": 17726592.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.3345,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-11T00:00:00+0000"
                },
                {
                    "open": 3.2505,
                    "high": 3.307,
                    "low": 3.2505,
                    "close": 3.276,
                    "volume": 16135851.0,
                    "adj_high": null,
                    "adj_low": null,
                    "adj_close": 3.276,
                    "adj_open": null,
                    "adj_volume": null,
                    "split_factor": 1.0,
                    "dividend": 0.0,
                    "symbol": "SAN.BMEX",
                    "exchange": "BMEX",
                    "date": "2023-07-10T00:00:00+0000"
                }
            ].map(element => ({ ...element, date: new Date(element.date) })).sort((a, b) => a.date - b.date));

    const [color, setColor] = useState(
        (props.color) ? props.color : ['#4fa1ff86']
    );

    const springs = useSpring({
        from: { opacity: 0, y: -5, scale: 0.9 },
        to: [{ opacity: 1, y: 0, scale: 1 }],
        config: {
            mass: 25,
            friction: 120,
            tension: 100,
        },
        delay: 0,
    });

    const svgDiv = useRef();

    useEffect(() => {

        const width = svgDiv.current.width.baseVal.value;
        const height = svgDiv.current.height.baseVal.value;
        // console.log(height)
        const margin = { top: 40, right: 40, bottom: 40, left: 40 };

        const svg = d3.select(svgDiv.current)
            .attr('width', width + margin.right + margin.left)
            .attr('height', height + margin.top + margin.bottom)
        const g = svg.append('g')
            .attr("transform", `translate(${margin.left},${margin.top + 25})`);

        const xScale = d3.scaleTime()
            .domain(d3.extent(data, d => d.date))
            .range([0, width]);

        const yScale = d3.scaleLinear()
            .domain([d3.min(data, d => d.close), d3.max(data, d => d.close)])
            .range([height - margin.top, 0]);

        const xAxis = (g) =>
            g.attr("transform", `translate(${margin.left},${height + margin.top-10})`).call(
                d3
                    .axisBottom(xScale)
                    .ticks(10)
                    .tickFormat(d3.utcFormat("%b-%y"))
                    .tickSizeOuter(0)
            )
                // .select(".domain").remove()
                .selectAll(".tick line")
                .attr("stroke", "white")


        const yAxis = g => g
            .attr("transform", `translate(${margin.left},${margin.top + 25})`)
            .call(d3.axisLeft(yScale))
            .call(g => g.select(".domain").remove())
            .call(g => g.select(".tick:last-of-type text").clone()
                .attr("x", 3)
                .attr("text-anchor", "start")
                .attr("font-weight", "bold")
                .text('Close'));


        const lg = svg
            .append("defs")
            .append("linearGradient") // linear gradient
            .attr("id", "mygrad")
            .attr("x1", "0%")
            .attr("x2", "0%")
            .attr("y1", "0%")
            .attr("y2", "100%");
        lg.append("stop")
            .attr("offset", "0%")
            .style("stop-color", color)
            .style("stop-opacity", 0.40);
        lg.append("stop")
            .attr("offset", "100%")
            .style("stop-color", color)
            .style("stop-opacity", 0.01);

        const area = d3
            .area()
            .curve(d3.curveCardinal.tension(0.95))
            .defined(function (d) {
                return d.close >= 0;
            })
            .x(function (d) {
                return xScale(d.date);
            })
            .y0(height - margin.bottom)
            .y1(function (d) {
                return yScale(d.close);
            });

        const line = d3.line()
            // .defined(d => !isNaN(d.close))
            .x(d => xScale(d.date))
            .y(d => yScale(d.close));


        // g.append("path")
        //     .datum(data)
        //     .style("stroke", `${color}`)
        //     .style("stroke-dasharray", "4.4")
        //     .attr('fill', 'none')
        //     .attr("d", line);

        g.append("path")
            .datum(data)
            .style("stroke", `${color}`)
            .style("stroke-width", `1.5`)
            .attr('fill', 'none')
            .attr("d", line)
            .call(transition);

        g
            .append("path")
            .datum(data)
            .style("fill", "url(#mygrad)")
            .style("stroke", "none")
            .attr("d", area)



        svg.append('g').call(xAxis)
            .selectAll('.tick text')
            .attr('style', 'transform: rotate(-60deg) translate(-25px, -10px);');;
        svg.append('g').call(yAxis);

        function transition(path) {
            path.transition()
                .duration(7500)
                .attrTween("stroke-dasharray", tweenDash)
                .on("start", () => { d3.select(this).call(transition); });
        };

        function tweenDash() {
            const l = this.getTotalLength(),
                i = d3.interpolateString("0," + l, l + "," + l);
            return function (t) { return i(t) };
        };
    }, []);

    // {        "open": 3.77,
    //         "high": 3.7765,
    //         "low": 3.756,
    //         "close": 3.768,
    //         "volume": 20252178.0,
    //         "adj_high": null,
    //         "adj_low": null,
    //         "adj_close": 3.768,
    //         "adj_open": null,
    //         "adj_volume": null,
    //         "split_factor": 1.0,
    //         "dividend": 0.0,
    //         "symbol": "SAN.BMEX",
    //         "exchange": "BMEX",
    //         "date": "2023-11-24T00:00:00+0000"}

    return (<>

        <animated.div
            style={{
                ...springs,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center'
            }}
        >

            <svg ref={svgDiv} height="30vh" width="40vw" preserveAspectRatio="xMaxYMax meet">
                <text x='20' fill="white" fontSize="1em" y="40" strokeWidth="0.1px" stroke="white">{title}</text>
            </svg>
        </animated.div>
    </>)
}