import { AgGridReact } from 'ag-grid-react'; // React Grid Logic
// import "ag-grid-community/styles/ag-grid.css"; // Core CSS
// import "ag-grid-community/styles/ag-theme-quartz.css"; // theme
import React, { useState } from 'react';

export const Table = () => {
    const data = [
        {
            "open": 13.95,
            "high": 14.155,
            "low": 13.94,
            "close": 14.135,
            "volume": 3147083.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 14.135,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "REP.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 54.0,
            "high": 55.2,
            "low": 54.0,
            "close": 55.1,
            "volume": 151952.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 55.1,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "ROVI.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 1.325,
            "high": 1.3395,
            "low": 1.32,
            "close": 1.326,
            "volume": 10747179.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 1.326,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "SAB.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 3.77,
            "high": 3.7765,
            "low": 3.756,
            "close": 3.768,
            "volume": 20252178.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 3.768,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "SAN.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 3.02,
            "high": 3.054,
            "low": 3.02,
            "close": 3.032,
            "volume": 1934716.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 3.032,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "SCYR.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 16.23,
            "high": 16.53,
            "low": 16.14,
            "close": 16.47,
            "volume": 566121.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 16.47,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "SLR.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 3.84,
            "high": 3.842,
            "low": 3.807,
            "close": 3.829,
            "volume": 7427236.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 3.829,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "TEF.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 1.03,
            "high": 1.038,
            "low": 1.019,
            "close": 1.02,
            "volume": 5227874.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 1.02,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "UNI.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 14.56,
            "high": 14.59,
            "low": 14.36,
            "close": 14.39,
            "volume": 376600.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 14.39,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "IDR.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 37.0,
            "high": 37.26,
            "low": 36.93,
            "close": 37.26,
            "volume": 1221468.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 37.26,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "ITX.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 23.68,
            "high": 23.88,
            "low": 23.68,
            "close": 23.8,
            "volume": 106101.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 23.8,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "LOG.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 2.086,
            "high": 2.098,
            "low": 2.076,
            "close": 2.096,
            "volume": 3173827.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 2.096,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "MAP.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 5.72,
            "high": 5.725,
            "low": 5.68,
            "close": 5.705,
            "volume": 195254.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 5.705,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "MEL.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 8.69,
            "high": 8.7,
            "low": 8.575,
            "close": 8.61,
            "volume": 432622.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 8.61,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "MRL.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 22.31,
            "high": 22.5,
            "low": 22.155,
            "close": 22.355,
            "volume": 133049.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 22.355,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "MTS.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 27.26,
            "high": 27.42,
            "low": 27.2,
            "close": 27.38,
            "volume": 131479.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 27.38,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "NTGY.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 15.09,
            "high": 15.185,
            "low": 15.06,
            "close": 15.165,
            "volume": 546015.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 15.165,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "RED.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 35.96,
            "high": 36.29,
            "low": 35.89,
            "close": 36.23,
            "volume": 315416.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 36.23,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "ACS.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 10.095,
            "high": 10.215,
            "low": 10.095,
            "close": 10.15,
            "volume": 527058.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 10.15,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "ACX.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 155.8,
            "high": 157.5,
            "low": 155.35,
            "close": 156.6,
            "volume": 92332.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 156.6,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "AENA.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
        {
            "open": 62.8,
            "high": 63.14,
            "low": 62.58,
            "close": 62.86,
            "volume": 340672.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 62.86,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "AMS.BMEX",
            "exchange": "BMEX",
            "date": "2023-11-24T00:00:00+0000"
        },
    ]
    const [rowData, setRowData] = useState([
        { mission: "Voyager", company: "NASA", location: "Cape Canaveral", date: "1977-09-05" },
        { mission: "Apollo 13", company: "NASA", location: "Kennedy Space Center", date: "1970-04-11" },
        { mission: "Falcon 9", company: "SpaceX", location: "Cape Canaveral", date: "2015-12-22" }
    ]);

    const [colDefs, setColDefs] = useState([
        { field: "mission" },
        { field: "company" },
        { field: "location" },
        { field: "date" },
    ]);



    return (<>
        <div className="" style={{ height: 500 }}>
        <AgGridReact rowData={rowData} columnDefs={colDefs} />
        </div>
    </>)

}