"""empty message

Revision ID: 030de1e858eb
Revises: 126def8f6728
Create Date: 2024-01-28 22:29:08.007727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030de1e858eb'
down_revision = '126def8f6728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updatelogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updatelogs')
    # ### end Alembic commands ###
