"""empty message

Revision ID: 1146aab38886
Revises: aa94e8be55a0
Create Date: 2024-01-24 14:51:57.417544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1146aab38886'
down_revision = 'aa94e8be55a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_portfolio_id_key', type_='unique')
        batch_op.drop_constraint('users_portfolio_id_fkey', type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_portfolio_id_fkey', 'portfolios', ['portfolio_id'], ['id'])
        batch_op.create_unique_constraint('users_portfolio_id_key', ['portfolio_id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
