"""empty message

Revision ID: 126def8f6728
Revises: d442613233ad
Create Date: 2024-01-28 21:27:48.165878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126def8f6728'
down_revision = 'd442613233ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
