"""empty message

Revision ID: 4339874aa7a6
Revises: c4afa4c66b9e
Create Date: 2024-01-28 20:43:30.554435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4339874aa7a6'
down_revision = 'c4afa4c66b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('data_end', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('crypto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto')
    # ### end Alembic commands ###
