"""empty message

Revision ID: 6eae246294d0
Revises: 1c2e995e44b5
Create Date: 2024-01-24 15:33:40.084926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eae246294d0'
down_revision = '1c2e995e44b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_subscription_id_key', type_='unique')
        batch_op.drop_constraint('users_subscription_id_fkey', type_='foreignkey')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_subscription_id_fkey', 'subscriptions', ['subscription_id'], ['id'])
        batch_op.create_unique_constraint('users_subscription_id_key', ['subscription_id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
