"""empty message

Revision ID: 70304b09f9cb
Revises: 7bd8b2091cb5
Create Date: 2024-01-13 14:23:53.350354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70304b09f9cb'
down_revision = '7bd8b2091cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
