"""empty message

Revision ID: 7bd8b2091cb5
Revises: a955c85e28bb
Create Date: 2024-01-01 10:52:13.979198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd8b2091cb5'
down_revision = 'a955c85e28bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('create_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices')
    # ### end Alembic commands ###
