"""empty message

Revision ID: 833616a9df35
Revises: 
Create Date: 2023-12-24 13:00:27.431233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833616a9df35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('create_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices')
    # ### end Alembic commands ###
