"""empty message

Revision ID: fcecaa2de281
Revises: 91d5872ec2c3
Create Date: 2024-01-26 00:04:08.798155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcecaa2de281'
down_revision = '91d5872ec2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfoliolist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfoliolist', schema=None) as batch_op:
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
