name: Scheduled Task

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Run script
        run: |
           pipenv run python src/api/test.py
